{
 "title": "02a_collection_network",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "otelcol server",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(rpc_server_duration_milliseconds_bucket{service_name=\"otelcol\"}[1m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(rpc_server_duration_milliseconds_bucket{service_name=\"otelcol\"}[1m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, rate(rpc_server_duration_milliseconds_bucket{service_name=\"otelcol\"}[1m]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "otelcol client",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(rpc_client_duration_milliseconds_bucket{service_name=\"otelcol\"}[1m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(rpc_client_duration_milliseconds_bucket{service_name=\"otelcol\"}[1m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, rate(rpc_client_duration_milliseconds_bucket{service_name=\"otelcol\"}[1m]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "gateway-1 server",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(rpc_server_duration_milliseconds_bucket{service_name=\"otelcol-gateway\", service_instance_id=\"gateway-1\"}[1m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(rpc_server_duration_milliseconds_bucket{service_name=\"otelcol-gateway\", service_instance_id=\"gateway-1\"}[1m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, rate(rpc_server_duration_milliseconds_bucket{service_name=\"otelcol-gateway\", service_instance_id=\"gateway-1\"}[1m]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "gateway-2 server",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(rpc_server_duration_milliseconds_bucket{service_name=\"otelcol-gateway\", service_instance_id=\"gateway-2\"}[1m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(rpc_server_duration_milliseconds_bucket{service_name=\"otelcol-gateway\", service_instance_id=\"gateway-2\"}[1m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, rate(rpc_server_duration_milliseconds_bucket{service_name=\"otelcol-gateway\", service_instance_id=\"gateway-2\"}[1m]))",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}